name: nail_studio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0 # Versi yang telah dikonfirmasi bekerja
  dio: ^5.3.0
  image_picker: ^1.0.7   # âœ… TAMBAHKAN INI




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/abstract_lines.jpg
    - assets/images/cosmic_pop.jpg
    - assets/images/french_manicure.jpeg
    - assets/images/glittery_ombre.jpg
    - assets/images/matte_nude.jpg
    - assets/images/product1.jpeg
    - assets/images/product2.jpeg
    - assets/images/product3.jpeg
    - assets/images/product4.jpeg
    - assets/images/product5.jpeg
    - assets/images/product6.jpeg
    - assets/images/summer_floral.jpg
